# Generated by Django 4.2 on 2025-02-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('pais_origen', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('año_lanzamiento', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_manager.artista')),
            ],
        ),
    ]
